services:
  - type: web
    name: ai-medical-report-analyzer
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r service/requirements.txt
    startCommand: uvicorn service.app:app --host 0.0.0.0 --port 10000
